# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

sudo: false

install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  
r_check_args: "--as-cran"

r_packages:
  - covr
  - maps
  - plotrix
  - sqldf
  - plyr
  - taxize
  - treemap
  - ggplot2
  - lattice
  - chron
  - leafletR
  - rgdal
  - rinat
  - covr
  - testthat
  

after_success:
  - Rscript -e 'library(covr); codecov()'
  